version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: progado_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: progado
      MYSQL_USER: progado
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_PROGADO}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - progado_db_data:/var/lib/mysql
    networks:
      - progado_network

  app:
    image: php:8-apache
    container_name: progado_app
    restart: always
    ports:
      - '127.0.0.1:8080:80'
    volumes:
      - ./api:/var/www/html
    environment:
      MYSQL_USER_PROGADO: progado
      MYSQL_PASSWORD_PROGADO: ${MYSQL_PASSWORD_PROGADO}
    depends_on:
      - db
    networks:
      - progado_network

volumes:
  progado_db_data:

networks:
  progado_network:
    driver: bridge
