version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: progado_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: progado
      MYSQL_USER: ${MYSQL_USER_PROGADO}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_PROGADO}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - progado_db_data:/var/lib/mysql
    networks:
      - progado_network

  app:
    image: php:8-apache
    container_name: progado_app
    restart: always
    # ports:
    #   - "127.0.0.1:8080:80"
    volumes:
      - ./api:/var/www/html
    command: >
      bash -c "a2enmod rewrite &&
      echo '<Directory /var/www/html/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
      </Directory>' > /etc/apache2/conf-enabled/php-custom.conf &&
      apache2ctl -D FOREGROUND"
    environment:
      MYSQL_USER_PROGADO: ${MYSQL_USER_PROGADO}
      MYSQL_PASSWORD_PROGADO: ${MYSQL_PASSWORD_PROGADO}
    depends_on:
      - db
    networks:
      - progado_network
      - dokploy-network
    labels:
      - "traefik.enable=true"

      # Router
      - "traefik.http.routers.progado.rule=Host(`proximoturno.com.br`) && PathPrefix(`/progado`)"
      - "traefik.http.routers.progado.entrypoints=websecure"
      - "traefik.http.routers.progado.tls=true"
      - "traefik.http.routers.progado.tls.certresolver=myresolver"
      - "traefik.http.routers.progado.service=progado"

      # Middleware
      - "traefik.http.middlewares.progado-strip.stripprefix.prefixes=/progado"
      - "traefik.http.routers.progado.middlewares=progado-strip"

      # Service
      - "traefik.http.services.progado.loadbalancer.server.port=80"

volumes:
  progado_db_data:

networks:
  progado_network:
    driver: bridge
  dokploy-network:
    external: true
